version: 0.2

phases:
  install:
    commands:
      - echo Checking Node.js version...
      - node --version

  pre_build:
    commands:
      - echo Installing server dependencies...
      - npm install
      - echo Installing client dependencies...
      - cd client
      - npm install
      - cd ..

  build:
    commands:
      - echo Build started...
      - npm run build
      - echo Build completed

  post_build:
    commands:
      - echo Build completed on both server and client.
