version: 0.2

phases:
  install:
    commands:
      - n latest

  pre_build:
    commands:
      - echo Installing server dependencies...
      - cd server
      - npm install
      - cd ..
      - echo Installing client dependencies...
      - cd client
      - npm install
      - cd ..

  build:
    commands:
      - echo Build started...
      - npm run build
      - echo Build completed

  post_build:
    commands:
      - echo Build completed on both server and client.
