version: 0.2

phases:
  install:
    commands:
      - echo Installing source NVM...
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install node
      - echo Finished installing NVM

  pre_build:
    commands:
      - echo Installing server dependencies...
      - npm install
      - echo Installing client dependencies...
      - cd client
      - npm install
      - cd ..

  build:
    commands:
      - echo Build started...
      - npm run build
      - echo Build completed

  post_build:
    commands:
      - echo Build completed on both server and client.
