version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Node.js...
      - node -v
      - echo Node.js installed successfully

  pre_build:
    commands:
      - echo Installing server dependencies...
      - cd server
      - npm install
      - cd ..
      - echo Installing client dependencies...
      - cd client
      - npm install
      - cd ..

  build:
    commands:
      - echo Build started on server...
      - cd server
      - npm run build
      - cd ..
      - echo Build started on client...
      - cd client
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo Build completed on both server and client.
