location /api/ {
proxy_pass http://localhost:8000/;
proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

sudo systemctl restart nginx


name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Backend Dependencies
        run: npm ci
      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install
      - name: Build React App
        env:
          CI: false
        working-directory: ./client
        run: npm run build --if-present
      - name: Restart PM2 Server
        run: |
          cd ..
          pm2 restart server
